apiVersion: v1
kind: Service
metadata:
  name: portfolio
  namespace: pet-projects
  labels:
    app: portfolio
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: portfolio